/**
 * @file splash_screen.c
 * @brief Scroll-up splash screen — ILI9341, SPI2, landscape 320×240.
 *
 * Animation: the image is revealed one row at a time, starting from the
 * bottom of the display and working upward.  Each row appears at its
 * correct final position, creating a smooth "scroll up into view" effect
 * with a single SPI row-write per step.
 *
 * Depends on image_rgb565.h (generated by png_to_rgb565.py).
 * That header must expose:
 *   const uint16_t splash_image[SPLASH_IMAGE_W * SPLASH_IMAGE_H];
 *   #define SPLASH_IMAGE_W  320
 *   #define SPLASH_IMAGE_H  240
 * Pixels are stored in little-endian RGB565 (byte-swapped) as required
 * by the ILI9341 on this board.
 */

#include "splash_screen.h"
#include "image_rgb565.h"      /* generated — see png_to_rgb565.py */

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/spi_master.h"
#include "driver/gpio.h"
#include "esp_log.h"

/* ── Pin definitions (HARDWARE.md) ─────────────────────────────── */
#define DISP_PIN_CS    9
#define DISP_PIN_DC    13
#define DISP_PIN_RST   48
#define DISP_PIN_CLK   12
#define DISP_PIN_MOSI  11
#define DISP_PIN_MISO  10
#define DISP_SPI_HOST  SPI2_HOST
#define DISP_SPI_FREQ  SPI_MASTER_FREQ_40M

/* ── Display geometry — landscape 320×240 ───────────────────────── */
#define SCREEN_W  320
#define SCREEN_H  240

/* ── Animation tuning ───────────────────────────────────────────── */
/* Delay between revealing each row (ms).  4 ms → ~1 s total scroll. */
#define SCROLL_ROW_DELAY_MS  4
/* How long to hold the completed image before returning (ms). */
#define SPLASH_HOLD_MS       2000

static const char *TAG = "splash";

static spi_device_handle_t s_spi;

/* ── DC-pin callback (called by SPI driver before each transaction) ─ */
/* t->user == 0 → command (DC low); t->user == 1 → data (DC high).   */
static void IRAM_ATTR spi_pre_transfer_cb(spi_transaction_t *t)
{
    gpio_set_level(DISP_PIN_DC, (int)(intptr_t)t->user);
}

/* ── Low-level helpers ──────────────────────────────────────────── */

static void disp_cmd(uint8_t cmd)
{
    spi_transaction_t t = {
        .length    = 8,
        .tx_data   = {cmd},
        .flags     = SPI_TRANS_USE_TXDATA,
        .user      = (void *)0,   /* DC = 0 */
    };
    ESP_ERROR_CHECK(spi_device_polling_transmit(s_spi, &t));
}

static void disp_data(const uint8_t *data, int len)
{
    if (len == 0) return;
    spi_transaction_t t = {
        .length    = (size_t)len * 8,
        .tx_buffer = data,
        .user      = (void *)1,   /* DC = 1 */
    };
    ESP_ERROR_CHECK(spi_device_polling_transmit(s_spi, &t));
}

/* ── Address window + RAMWR ─────────────────────────────────────── */
static void ili9341_set_window(uint16_t x0, uint16_t y0,
                               uint16_t x1, uint16_t y1)
{
    uint8_t d[4];

    disp_cmd(0x2A);  /* CASET */
    d[0] = x0 >> 8; d[1] = x0 & 0xFF;
    d[2] = x1 >> 8; d[3] = x1 & 0xFF;
    disp_data(d, 4);

    disp_cmd(0x2B);  /* PASET */
    d[0] = y0 >> 8; d[1] = y0 & 0xFF;
    d[2] = y1 >> 8; d[3] = y1 & 0xFF;
    disp_data(d, 4);

    disp_cmd(0x2C);  /* RAMWR — pixels follow */
}

/* ── Write one row of pre-swapped RGB565 pixels ─────────────────── */
static void write_row(uint16_t screen_y, const uint16_t *pixels)
{
    ili9341_set_window(0, screen_y, SCREEN_W - 1, screen_y);
    spi_transaction_t t = {
        .length    = SCREEN_W * 16,
        .tx_buffer = pixels,
        .user      = (void *)1,   /* DC = 1 */
    };
    ESP_ERROR_CHECK(spi_device_polling_transmit(s_spi, &t));
}

/* ── Clear entire screen to black ───────────────────────────────── */
static void clear_screen(void)
{
    static const uint8_t black_row[SCREEN_W * 2] = {0};

    /* Set window to full screen, then stream all rows */
    ili9341_set_window(0, 0, SCREEN_W - 1, SCREEN_H - 1);
    spi_transaction_t t = {
        .length    = SCREEN_W * 16,
        .tx_buffer = black_row,
        .user      = (void *)1,
    };
    for (int y = 0; y < SCREEN_H; y++) {
        ESP_ERROR_CHECK(spi_device_polling_transmit(s_spi, &t));
    }
}

/* ── ILI9341 hardware reset ─────────────────────────────────────── */
static void ili9341_hw_reset(void)
{
    gpio_set_level(DISP_PIN_RST, 0);
    vTaskDelay(pdMS_TO_TICKS(10));
    gpio_set_level(DISP_PIN_RST, 1);
    vTaskDelay(pdMS_TO_TICKS(120));
}

/* ── ILI9341 register initialisation ───────────────────────────── */
static void ili9341_init_regs(void)
{
    disp_cmd(0x01);                         /* Software reset */
    vTaskDelay(pdMS_TO_TICKS(150));

    disp_cmd(0xEF);
    disp_data((uint8_t[]){0x03, 0x80, 0x02}, 3);

    disp_cmd(0xCF);
    disp_data((uint8_t[]){0x00, 0xC1, 0x30}, 3);

    disp_cmd(0xED);
    disp_data((uint8_t[]){0x64, 0x03, 0x12, 0x81}, 4);

    disp_cmd(0xE8);
    disp_data((uint8_t[]){0x85, 0x00, 0x78}, 3);

    disp_cmd(0xCB);
    disp_data((uint8_t[]){0x39, 0x2C, 0x00, 0x34, 0x02}, 5);

    disp_cmd(0xF7);
    disp_data((uint8_t[]){0x20}, 1);

    disp_cmd(0xEA);
    disp_data((uint8_t[]){0x00, 0x00}, 2);

    disp_cmd(0xC0);                         /* Power control 1 */
    disp_data((uint8_t[]){0x23}, 1);

    disp_cmd(0xC1);                         /* Power control 2 */
    disp_data((uint8_t[]){0x10}, 1);

    disp_cmd(0xC5);                         /* VCOM control */
    disp_data((uint8_t[]){0x3E, 0x28}, 2);

    disp_cmd(0xC7);                         /* VCOM control 2 */
    disp_data((uint8_t[]){0x86}, 1);

    /*
     * MADCTL — landscape 320×240, BGR colour filter.
     * MV=1 (row/col swap), MX=1 (mirror X), BGR=1 → 0x68.
     * If the image appears mirrored or rotated, try 0x28, 0x48, 0xA8, 0xE8.
     */
    disp_cmd(0x36);
    disp_data((uint8_t[]){0x68}, 1);

    disp_cmd(0x3A);                         /* Pixel format: 16-bit */
    disp_data((uint8_t[]){0x55}, 1);

    disp_cmd(0xB1);                         /* Frame rate ~70 Hz */
    disp_data((uint8_t[]){0x00, 0x18}, 2);

    disp_cmd(0xB6);                         /* Display function control */
    disp_data((uint8_t[]){0x08, 0x82, 0x27}, 3);

    disp_cmd(0xF2);                         /* 3-gamma disable */
    disp_data((uint8_t[]){0x00}, 1);

    disp_cmd(0x26);                         /* Gamma curve 1 */
    disp_data((uint8_t[]){0x01}, 1);

    disp_cmd(0xE0);                         /* Positive gamma */
    disp_data((uint8_t[]){0x0F,0x31,0x2B,0x0C,0x0E,0x08,
                           0x4E,0xF1,0x37,0x07,0x10,0x03,
                           0x0E,0x09,0x00}, 15);

    disp_cmd(0xE1);                         /* Negative gamma */
    disp_data((uint8_t[]){0x00,0x0E,0x14,0x03,0x11,0x07,
                           0x31,0xC1,0x48,0x08,0x0F,0x0C,
                           0x31,0x36,0x0F}, 15);

    disp_cmd(0x11);                         /* Sleep out */
    vTaskDelay(pdMS_TO_TICKS(120));

    disp_cmd(0x29);                         /* Display on */
}

/* ── SPI bus + display device setup ────────────────────────────── */
static void spi_and_gpio_init(void)
{
    /* DC and RST as push-pull outputs */
    gpio_config_t io = {
        .pin_bit_mask = (1ULL << DISP_PIN_DC) | (1ULL << DISP_PIN_RST),
        .mode         = GPIO_MODE_OUTPUT,
        .pull_up_en   = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE,
    };
    ESP_ERROR_CHECK(gpio_config(&io));

    /* SPI2 bus (shared with SD card — SD-CS is handled separately) */
    spi_bus_config_t bus = {
        .mosi_io_num     = DISP_PIN_MOSI,
        .miso_io_num     = DISP_PIN_MISO,
        .sclk_io_num     = DISP_PIN_CLK,
        .quadwp_io_num   = -1,
        .quadhd_io_num   = -1,
        .max_transfer_sz = SCREEN_W * 2 + 8,
    };
    ESP_ERROR_CHECK(spi_bus_initialize(DISP_SPI_HOST, &bus, SPI_DMA_CH_AUTO));

    /* Display device */
    spi_device_interface_config_t dev = {
        .clock_speed_hz = DISP_SPI_FREQ,
        .mode           = 0,            /* CPOL=0, CPHA=0 */
        .spics_io_num   = DISP_PIN_CS,
        .queue_size     = 7,
        .pre_cb         = spi_pre_transfer_cb,
    };
    ESP_ERROR_CHECK(spi_bus_add_device(DISP_SPI_HOST, &dev, &s_spi));
}

/* ── Public API ─────────────────────────────────────────────────── */

void splash_screen_run(void)
{
    ESP_LOGI(TAG, "Initialising SPI2 and ILI9341...");
    spi_and_gpio_init();
    ili9341_hw_reset();
    ili9341_init_regs();

    ESP_LOGI(TAG, "Clearing display...");
    clear_screen();

    ESP_LOGI(TAG, "Starting scroll-up animation (%d rows, %d ms/row)...",
             SCREEN_H, SCROLL_ROW_DELAY_MS);

    /*
     * Reveal the image from the bottom row of the screen upward.
     * At each step, the next row of the image is written at its final
     * screen position.  The image appears to scroll up into view.
     *
     * splash_image row layout: row 0 is the top of the image.
     * We write row (SCREEN_H-1) first (bottom of image → bottom of screen),
     * then row (SCREEN_H-2), … row 0 (top of image → top of screen).
     */
    for (int img_row = SCREEN_H - 1; img_row >= 0; img_row--) {
        write_row((uint16_t)img_row,
                  splash_image + (size_t)img_row * SCREEN_W);
        if (SCROLL_ROW_DELAY_MS > 0) {
            vTaskDelay(pdMS_TO_TICKS(SCROLL_ROW_DELAY_MS));
        }
    }

    ESP_LOGI(TAG, "Splash complete. Holding for %d ms.", SPLASH_HOLD_MS);
    vTaskDelay(pdMS_TO_TICKS(SPLASH_HOLD_MS));
}
